"""Application-owned tenancy and identity foundation for Chirp Workspace products."""

from .auth import WorkspaceUserLoader, chirp_auth_config
from .errors import (
    AuthenticationError,
    AuthorizationError,
    ConflictError,
    DatabaseUnavailableError,
    DuplicateInvitationError,
    InvitationConsumedError,
    InvitationError,
    InvitationExpiredError,
    InvitationRevokedError,
    LastOwnerError,
    NotFoundError,
    PasswordResetConsumedError,
    PasswordResetError,
    PasswordResetExpiredError,
    PasswordResetRevokedError,
    SchemaMismatchError,
    TenantMismatchError,
    ValidationError,
    WorkspaceCoreError,
)
from .models import (
    AuditEvent,
    AuditEventId,
    BootstrapResult,
    BootstrapState,
    Invitation,
    InvitationAcceptance,
    InvitationId,
    IssuedInvitation,
    IssuedPasswordReset,
    Membership,
    MembershipId,
    PasswordReset,
    PasswordResetId,
    Role,
    UserId,
    Workspace,
    WorkspaceId,
    WorkspacePrincipal,
    WorkspaceUser,
    new_id,
)
from .permissions import Permission, has_permission, permissions_for_role, require_permission
from .repository import WorkspaceRepository

__all__ = [
    "AuditEvent",
    "AuditEventId",
    "AuthenticationError",
    "AuthorizationError",
    "BootstrapResult",
    "BootstrapState",
    "ConflictError",
    "DatabaseUnavailableError",
    "DuplicateInvitationError",
    "Invitation",
    "InvitationAcceptance",
    "InvitationConsumedError",
    "InvitationError",
    "InvitationExpiredError",
    "InvitationId",
    "InvitationRevokedError",
    "IssuedInvitation",
    "IssuedPasswordReset",
    "LastOwnerError",
    "Membership",
    "MembershipId",
    "NotFoundError",
    "PasswordReset",
    "PasswordResetConsumedError",
    "PasswordResetError",
    "PasswordResetExpiredError",
    "PasswordResetId",
    "PasswordResetRevokedError",
    "Permission",
    "Role",
    "SchemaMismatchError",
    "TenantMismatchError",
    "UserId",
    "ValidationError",
    "Workspace",
    "WorkspaceCoreError",
    "WorkspaceId",
    "WorkspacePrincipal",
    "WorkspaceRepository",
    "WorkspaceUser",
    "WorkspaceUserLoader",
    "chirp_auth_config",
    "has_permission",
    "new_id",
    "permissions_for_role",
    "require_permission",
]
